// Workspace-wide flat config. Fast, non-type-aware linting: the goal is the
// drift tsc tolerates (unused imports/vars, hook-dependency mistakes, foot-gun
// syntax), not a second typechecker — `pnpm run typecheck` owns type errors.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/static-build/**",
      "**/node_modules/**",
      "**/.expo/**",
      "tmp/**",
      "**/*.d.ts",
      // Generated clients — regenerated by `api-spec run codegen`, never edited.
      "lib/api-zod/src/generated/**",
      "lib/api-zod/src/index.ts",
      "lib/api-client-react/**",
    ],
  },

  // Plain JS: build scripts, the e2e harness, config files. Node globals.
  {
    files: ["**/*.{js,mjs,cjs}"],
    ...js.configs.recommended,
    languageOptions: {
      globals: { ...globals.node },
    },
  },

  // Service workers ship as static assets and run against the SW global scope.
  {
    files: ["**/public/sw.js"],
    languageOptions: {
      globals: { ...globals.serviceworker },
    },
  },

  // TypeScript everywhere.
  ...tseslint.configs.recommended.map((c) => ({
    ...c,
    files: ["**/*.{ts,tsx}"],
  })),
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      // The reason this config exists: tsconfig runs with noUnusedLocals off,
      // so unused imports and locals accumulate silently without this.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Pragmatic: `any` is used deliberately at test/glue boundaries; the
      // typed surface is enforced by the generated clients and zod parsing.
      "@typescript-eslint/no-explicit-any": "off",
    },
  },

  // React hook correctness for shared UI, every web app and mobile. Hooks also live in
  // plain .ts files (e.g. use-voice-recorder.ts), so cover both extensions.
  {
    files: [
      "artifacts/console/src/**/*.{ts,tsx}",
      "artifacts/sme-compliance/src/**/*.{ts,tsx}",
      "artifacts/buyer-portal/src/**/*.{ts,tsx}",
      "artifacts/landing/src/**/*.{ts,tsx}",
      "artifacts/penalty-calculator/src/**/*.{ts,tsx}",
      "artifacts/mobile/**/*.{ts,tsx}",
      "lib/web-ui/src/**/*.{ts,tsx}",
    ],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "error",
    },
  },
);
